// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEWfCayH9fIKIxVffTQKqz9poCmgIs4Dc',
    appId: '1:182192356671:web:273b182ff65491e305678a',
    messagingSenderId: '182192356671',
    projectId: 'umdlostandfound',
    authDomain: 'umdlostandfound.firebaseapp.com',
    storageBucket: 'umdlostandfound.appspot.com',
    measurementId: 'G-M1WRWXW1R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs6YSPoVRQk8hsPddjWUnpTBmuGJJI3iQ',
    appId: '1:182192356671:android:88de2f4de4ac219305678a',
    messagingSenderId: '182192356671',
    projectId: 'umdlostandfound',
    storageBucket: 'umdlostandfound.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdclxISS6_tEQVh6JTmd8wAzINMAVj8LQ',
    appId: '1:182192356671:ios:9ae00184bb1feac105678a',
    messagingSenderId: '182192356671',
    projectId: 'umdlostandfound',
    storageBucket: 'umdlostandfound.appspot.com',
    iosBundleId: 'com.example.mapTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdclxISS6_tEQVh6JTmd8wAzINMAVj8LQ',
    appId: '1:182192356671:ios:cbe05c45469a996205678a',
    messagingSenderId: '182192356671',
    projectId: 'umdlostandfound',
    storageBucket: 'umdlostandfound.appspot.com',
    iosBundleId: 'com.example.mapTest.RunnerTests',
  );
}
