// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArqkKKyMTuMd0j-lUjR3D6sNIh786WG9I',
    appId: '1:602266855191:web:f9d95fb7876582ff81b952',
    messagingSenderId: '602266855191',
    projectId: 'umdlostandfoundbeta',
    authDomain: 'umdlostandfoundbeta.firebaseapp.com',
    storageBucket: 'umdlostandfoundbeta.appspot.com',
    measurementId: 'G-JEV3EJNRT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdQWQVI8H9xF-kuNmmsn0WItVLYiEtKQ',
    appId: '1:602266855191:android:e8616029cc01e09681b952',
    messagingSenderId: '602266855191',
    projectId: 'umdlostandfoundbeta',
    storageBucket: 'umdlostandfoundbeta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCprkUNOYOpRz8Lyjz65jOrZ9pq7hMjaFk',
    appId: '1:602266855191:ios:194482cd12ee8ca181b952',
    messagingSenderId: '602266855191',
    projectId: 'umdlostandfoundbeta',
    storageBucket: 'umdlostandfoundbeta.appspot.com',
    iosBundleId: 'com.example.mapTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCprkUNOYOpRz8Lyjz65jOrZ9pq7hMjaFk',
    appId: '1:602266855191:ios:d52a618b34c69dec81b952',
    messagingSenderId: '602266855191',
    projectId: 'umdlostandfoundbeta',
    storageBucket: 'umdlostandfoundbeta.appspot.com',
    iosBundleId: 'com.example.mapTest.RunnerTests',
  );
}
